# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://n23dccn082_db_user:35351235@cluster0.qg1imwv.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=taskmaster_db

server.port=8080

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenminhdaiduongtest1@gmail.com
# password mail app
spring.mail.password=awefbvjtwjdljnwe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
